### ISSUE TITLE
saml-advanced-role-idp-mapper support

### ISSUE THREAD

**Issue by davide-talesco** [pulumi/pulumi-keycloak#109]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Keycloak supports SAML Advanced Attribute to Role mapper type but I could not find it in Pulumi Keycloak Provider.

Am I missing something or is it just not implemented?

### Affected area/feature

SAML Identity Provider

Regards,
Davide

**Comment by SRodi** [comment]
Hi @davide-talesco, for this you can use `CustomIdentityProviderMapping`.

For example in `TypeScript`:

```ts
    const myRealmRoleMapper = new keycloak.CustomIdentityProviderMapping("myRealmRoleMapper", {
      name: "myRealmRoleMapper",
      realm: myRealm.realm,
      identityProviderAlias: myRealmSamlIdentityProvider.alias,
      identityProviderMapper: "saml-advanced-role-idp-mapper",
      extraConfig: {
        attributes: "[{\"key\":\"groups\",\"value\":\"Something\"}]",
        role: realmRoleMyRole.name
      },
    });
```

**Comment by davide-talesco** [comment]
@SRodi thanks it works!
