### ISSUE TITLE
Provide example for customIdentityProviderMapping

### ISSUE THREAD

**Issue by raben2** [pulumi/pulumi-keycloak#114]
File: [themes/default/content/registry/packages/keycloak/api-docs/customidentityprovidermapping/_index.md](https://www.pulumi.com/registry/packages/keycloak/api-docs/customidentityprovidermapping/)

```
const customMapper = new CustomIdentityProviderMapping("custom-mapper", {
    realm: 'myRealm',
    identityProviderAlias: 'oidc',
    identityProviderMapper: 'oidc-advanced-group-idp-mapper',
    name: 'claimToGroupMapper',
    extraConfig: {
        syncMode: 'INHERIT',
        claims: "[{\"key\":\"Type\",\"value\":\"Custom\"}]" ,
        group: 'CustomTypes'
    }
});
```

Alternatively you can use this to map a IDP claim to a role by setting the `identityProviderMapper: oidc-advanced-role-idp-mapper`

**Comment by danielrbradley** [comment]
Hi, the ID in the for the import is just an example of the value, this should be changed for your specific scenario.

The value `my-mapper` is an example of an `idp_alias`.

These examples are generated from the upstream terraform source so would have to be addressed there if need, so I will close in this repo.
