### ISSUE TITLE
Missing docs and only partially translated

### ISSUE THREAD

**Issue by johnbaro** [pulumi/pulumi-keycloak#143]
File: [themes/default/content/registry/packages/keycloak/api-docs/openid/client/_index.md](https://www.pulumi.com/registry/packages/keycloak/api-docs/openid/client/)

This page is missing docs compared to the [source](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docs/resources/openid_client.md): 
E.g. [accessType](https://www.pulumi.com/registry/packages/keycloak/api-docs/openid/client/#state_accesstype_nodejs) states:
> Specifies the type of client, which can be one of the following:

but does not have any following text. 

Compared to [openid_client](https://github.com/mrparkers/terraform-provider-keycloak/blob/master/docs/resources/openid_client.md) which has the relevant following text.

As well, [authorization](https://www.pulumi.com/registry/packages/keycloak/api-docs/openid/client/#state_authorization_nodejs) references `access_type` but pulumi translates this to `accessType` as above.

If these docs are curated I'll send a PR.

**Comment by mjeffryes** [comment]
We're not able to extract the description for the API reference for this parameter, but it looks like the full docs are available with the examples now: [keycloak.openid.Client | Pulumi Registry](https://www.pulumi.com/registry/packages/keycloak/api-docs/openid/client/#argument-reference)
