### ISSUE TITLE
Keycloak Client post_logout_redirect_uri Support

### ISSUE THREAD

**Issue by SimplicityApks** [pulumi/pulumi-keycloak#157]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Recent keycloak (>v19) has introduced the client parameter `post_logout_redirect_uri` specifying the valid URIs a client may redirect to after logout. [See the logout docs](https://www.keycloak.org/docs/latest/server_admin/#rp-initiated-logout).
It would be nice if pulumi gained support for this, as Keycloak by default does not allow any redirect. So in order for logout to work currently have to spam "+" into this field in every realm manually ;)

**Comment by guineveresaenger** [comment]
Hi @SimplicityApks - thank you for filing this issue!

While we are [awaiting upstream changes](https://github.com/mrparkers/terraform-provider-keycloak/issues/740) that will properly add this as an attribute to the Client resource, per that same upstream discussion, you should be able to leverage [the ExtraConfig option](https://www.pulumi.com/registry/packages/keycloak/api-docs/openid/client/#extraconfig_nodejs) to set this in the meantime.

**Comment by mikhailshilkov** [comment]
Closing since the upstream issue was fixed a while ago
