### ISSUE TITLE
Problem creating ExecutionConfig

### ISSUE THREAD

**Issue by mj-rittermann** [pulumi/pulumi-keycloak#222]
When we try to deploy an ExecutionConfig we constantly get an 409 error returned: 

 * error sending POST request to /admin/realms/xxxxxx/authentication/executions/b2c11041-fc59-4ca3-8871-5d66ada8339f/config: 409 Conflict. Response body: {"error":"unknown_error"}

We have validated that the alias and config are correctly set in the pulumi script, by creating the ExecutionConfig manually in keycloak and import it to the pulumi stack

```
_ = new Pulumi.Keycloak.Authentication.ExecutionConfig("custom_first_broker_login_execution_configA", new()
{
    RealmId = realm.Id,
    ExecutionId = reviewUserInfoStep.Id,
    Alias = "review profile config",
    Config =
    {
        { "update.profile.on.first.login", "off" },
    },
}, new() 
{ 
    DependsOn = { reviewUserInfoStep },
    Provider = _provider,
    Protect = false
});
```

When the snippet above is executed we get the following error in the keycloak console:

```
2023-05-22 07:46:18,879 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-77) SQL Error: 0, SQLState: 23505
2023-05-22 07:46:18,879 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (executor-thread-77) ERROR: duplicate key value violates unique constraint "constraint_auth_pk"
  Detail: Key (id)=() already exists.
```

We took a short look into the underlying pulumi code, which indicates the id of the ExecutionConfig is being set to "" when executed, which explains the duplicate key error above.

https://github.com/pulumi/pulumi-keycloak/blob/922a8ecb6557e9e61ef7df8ae59e0fa01bb00a11/sdk/dotnet/Authentication/ExecutionConfig.cs#L102

https://github.com/pulumi/pulumi-keycloak/blob/922a8ecb6557e9e61ef7df8ae59e0fa01bb00a11/sdk/dotnet/Authentication/ExecutionConfig.cs#L111

Hope someone has the time to look into this issues, as we currently have to do the above configuration manually.

**Comment by aq17** [comment]
Hi @mj-rittermann , thanks for opening the issue. It appears this was an [upstream bug](https://github.com/mrparkers/terraform-provider-keycloak/issues/839) that is on track to be fixed. We will release a new version once there is a new upstream release.

**Comment by dglozano** [comment]
Upgrading to v5.2.1 solved it for me, as it contains the upgraded upstream library with the fix
