### ISSUE TITLE
Get on `authentication.Flow` requires the parameter `ID`.

### ISSUE THREAD

**Issue by RyanS-J** [pulumi/pulumi-keycloak#398]
### What happened?

I'm trying to lookup and existing flow and this seems impossible.

Within the [docs](authentication.Flow) there is a required parameter `id`. Given that this is a unique ID and I'm trying to lookup a built-in flow there is no way to get this ID using automation so it makes it impossible to update existing flows unless you hardcode or manually provide the flow ID. This makes the get completely useless.

### Example

```
flow_name = "first broker login"
# How do I get the ID?
auth_flow = keycloak.authentication.Flow.get(resource_name=flow_name, realm_id=realm.id)
```

Results in `TypeError: Flow.get() missing 1 required positional argument: 'id'` 

### Output of `pulumi about`
```
CLI
Version      3.100.0
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.49.0
azure-native  2.28.0
azuread       5.47.0
keycloak      5.2.1
mailgun       3.4.1
opsgenie      1.2.9
pagerduty     4.3.1
python        unknown
random        4.13.4

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

This project is written in python: executable='C:\Python311\python.exe' version='3.11.6'

`<Redacted>`

Backend
Name           pulumi.com
URL            https://app.pulumi.com/`<Redacted>`
User           `<Redacted>`
Organizations  `<Redacted>`
Token type     `<Redacted>`

Dependencies:
NAME              VERSION
appm              0.0.0
cryptography      42.0.2
keycloak          3.1.4
pip               23.2.1
pulumi-azure      5.49.0
pulumi-keycloak   5.2.1
pulumi-mailgun    3.4.1
pulumi-opsgenie   1.2.9
pulumi-pagerduty  4.3.1
setuptools        68.2.2
wheel             0.41.2

```

### Additional context
I can not hardcode or provide the flow ID as realm(s) are created within the same automation.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @RyanS-J. I'm sorry you're not finding this helpful. 

Pulumi's [`get`](https://www.pulumi.com/docs/concepts/resources/get/) methods are used to bring an existing (and already identified) resource into Pulumi so it's outputs are consumable. It will not allow you to update the resource that you `get`.

Most uses of `get` that I have seen get their ID from hardcoded values, IDs from another Pulumi stack, or IDs discovered from the underlying API.
