### ISSUE TITLE
Upstream repo is abandoned

### ISSUE THREAD

**Issue by phil9909** [pulumi/pulumi-keycloak#573]
Pull Requests are not reviewed or merged.
Issues are not addressed.

> Since this repo doesn't receive lot of merged as mrparkers doesn't use keycloak anymore
> https://github.com/mrparkers/terraform-provider-keycloak/pull/937#issuecomment-2179087456

I guess this will eventually become a problem when e.g. KeyCloak makes some API change or the terraform bridge requires a more recent version of the terrafrom sdk, etc.

**Comment by guineveresaenger** [comment]
Thank you for alerting us with this update, @phil9909. We will need to discuss internally what direction to take.

**Comment by iwahbe** [comment]
It looks like keycloak has adopted the provider. Releases are going out again.
