### ISSUE TITLE
Change GetClientArgs to Input<String>

### ISSUE THREAD

**Issue by eduanb** [pulumi/pulumi-keycloak#77]
After I create a realm with Pulumi, I would like to get some of the default clients.
This code does not work because `realmId` is just a string and `realm.id` is an `Output<String>`. AFAIK there is no way of changing an `Output<String>` to just `String` in Pulumi. 
```
const realm = new keycloak.Realm(`${prefix}-realm`, {
    accessCodeLifespan: "1h",
    displayName: "My Realm",
    enabled: true,
    realm: "my-realm",
    sslRequired: "all",
    loginWithEmailAllowed: true
}, {provider: keycloakProvider});

const realmManagementClient = keycloak.openid.getClient({
    realmId: realm.id,
    clientId: "realm-management",
}, {provider: keycloakProvider});
```

In other resources like `Client` the realm is `Input<String>` so would make sense here too.

**Comment by lblackstone** [comment]
That does sound like a reasonable request. In the meantime, you could create the `realmManagementClient` inside an apply:

```typescript
realm.apply(r => keycloak.openid.getClient({
    realmId: r,
   ...
```

**Comment by lblackstone** [comment]
Actually, just found an [underlying issue](https://github.com/pulumi/pulumi/issues/5758), so I'm going to close this as a duplicate.
